build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.11
base_images:
  base:
    name: centos
    namespace: openshift
    tag: '7'
binary_build_commands: |
  go get -u github.com/Masterminds/glide && glide install --strip-vendor
  mkdir -p /tmp/artifacts
images:
- dockerfile_path: Dockerfile
  from: src
  to: osde2e-binary
promotion:
  name: master
  namespace: osde2e
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:

# PR check
- as: verify
  artifact_dir: /tmp/artifacts
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    ci/prow_pr_check.sh
  container:
    from: src

# Tests
# --- Integration
- as: e2e-int-4.1
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: osde2e-binary
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=int
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export TESTGRID_PREFIX=logs/osd-int-4.1

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
- as: e2e-int-4.2
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=int
    export MAJOR_TARGET=4
    export MINOR_TARGET=2
    export TESTGRID_PREFIX=logs/osd-int-4.2

    ci/prow_run_tests.sh /usr/local/osde2e-secrets

# --- Stage
- as: e2e-stage-4.1
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=stage
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export TESTGRID_PREFIX=logs/osd-stage-4.1

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
- as: e2e-stage-4.2
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=stage
    export MAJOR_TARGET=4
    export MINOR_TARGET=2
    export TESTGRID_PREFIX=logs/osd-stage-4.2

    ci/prow_run_tests.sh /usr/local/osde2e-secrets

# --- Production
- as: e2e-prod-4.1
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=prod
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export TESTGRID_PREFIX=logs/osd-prod-4.1

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
#- as: e2e-prod-4.2
#  artifact_dir: /tmp/artifacts
#  cron: '* */4 * * *'
#  secret:
#    name: osde2e-secrets
#    mount_path: /usr/local/osde2e-secrets
#  container:
#    from: bin
#  commands: |
#    set -o pipefail
#
#    export HOME=$(mktemp -d)
#
#    export REPORT_DIR=/tmp/artifacts
#
#    export OSD_ENV=prod
#    export MAJOR_TARGET=4
#    export MINOR_TARGET=2
#    export TESTGRID_PREFIX=logs/osd-prod-4.
#
#    ci/prow_run_tests.sh /usr/local/osde2e-secrets

# Upgrades
# --- Integration
- as: e2e-int-4.1-4.1
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=int
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export UPGRADE_RELEASE_STREAM=4.1.0-0.nightly
    export TESTGRID_PREFIX=logs/osd-upgrade-int-4.1-4.1

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
- as: e2e-int-4.1-4.2
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=int
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export UPGRADE_RELEASE_STREAM=4.2.0-0.nightly
    export TESTGRID_PREFIX=logs/osd-upgrade-int-4.1-4.2

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
- as: e2e-int-4.2-4.2
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=int
    export MAJOR_TARGET=4
    export MINOR_TARGET=2
    export UPGRADE_RELEASE_STREAM=4.2.0-0.nightly
    export TESTGRID_PREFIX=logs/osd-upgrade-int-4.2-4.2

    ci/prow_run_tests.sh /usr/local/osde2e-secrets

# --- Stage
- as: e2e-stage-4.1-4.1
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=stage
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export UPGRADE_RELEASE_STREAM=stable-4.1
    export TESTGRID_PREFIX=logs/osd-upgrade-stage-4.1-4.1

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
- as: e2e-stage-4.1-4.2
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=stage
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export UPGRADE_RELEASE_STREAM=fast-4.2
    export TESTGRID_PREFIX=logs/osd-upgrade-stage-4.1-4.2

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
- as: e2e-stage-4.2-4.2
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=stage
    export MAJOR_TARGET=4
    export MINOR_TARGET=2
    export UPGRADE_RELEASE_STREAM=fast-4.2
    export TESTGRID_PREFIX=logs/osd-upgrade-stage-4.2-4.2

    ci/prow_run_tests.sh /usr/local/osde2e-secrets

# --- Production
- as: e2e-prod-4.1-4.1
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=prod
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export UPGRADE_RELEASE_STREAM=stable-4.1
    export TESTGRID_PREFIX=logs/osd-upgrade-prod-4.1-4.1

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
- as: e2e-prod-4.1-4.2
  artifact_dir: /tmp/artifacts
  cron: '* */4 * * *'
  secret:
    name: osde2e-secrets
    mount_path: /usr/local/osde2e-secrets
  container:
    from: bin
  commands: |
    set -o pipefail

    export HOME=$(mktemp -d)

    export REPORT_DIR=/tmp/artifacts

    export OSD_ENV=prod
    export MAJOR_TARGET=4
    export MINOR_TARGET=1
    export UPGRADE_RELEASE_STREAM=fast-4.2
    export TESTGRID_PREFIX=logs/osd-upgrade-prod-4.1-4.2

    ci/prow_run_tests.sh /usr/local/osde2e-secrets
#- as: e2e-prod-4.2-4.2
#  artifact_dir: /tmp/artifacts
#  cron: '* */4 * * *'
#  secret:
#    name: osde2e-secrets
#    mount_path: /usr/local/osde2e-secrets
#  container:
#    from: bin
#  commands: |
#    set -o pipefail
#
#    export HOME=$(mktemp -d)
#
#    export REPORT_DIR=/tmp/artifacts
#
#    export OSD_ENV=prod
#    export MAJOR_TARGET=4
#    export MINOR_TARGET=2
#    export UPGRADE_RELEASE_STREAM=fast-4.2
#    export TESTGRID_PREFIX=logs/osd-upgrade-prod-4.2-4.2
#
#    ci/prow_run_tests.sh /usr/local/osde2e-secrets
